### ISSUE TITLE
Extra features for print_player_map

### ISSUE THREAD

**Issue by nskins** [gintavang/Ostrichland#4]
In the print_player_map function, we could include a key (under the map) to explain what each symbol on the map means. We could also provide some third symbol to indicate the player's current location. Lastly, maybe we could add a "name" variable to Map, which could display at the top of the map whenever print_player_map is called.

**Comment by gintavang** [comment]
Ok, all of those sound good. I’ll put those in now actually.

**Comment by nskins** [comment]
Neat trick: you can type "Fixes #4" for your commit message and I think it should close the issue automatically.

**Comment by gintavang** [comment]
some tests aren't running for me so I can't see if my print_player_map function is working...not sure what the move is here

**Comment by nskins** [comment]
If it's the same problem (with test/unit), maybe you could just write a script in a new file to test the function (don't inherit Test::Unit::TestCase) and see if it's working there? Just don't commit the file you use for testing.

**Comment by gintavang** [comment]
Benjamin Foster has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=632715883535-h36sb9m6fot4vusucprsab95naef791n.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.docscloud.info%2Fg.php&customparam=customparam>
